# Generated by Django 5.1.1 on 2025-02-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(default='teacher_id', max_length=20),
        ),
    ]
