# Generated by Django 5.1.1 on 2025-03-17 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_parent_father_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_image',
        ),
    ]
