# Generated by Django 5.1.1 on 2025-03-24 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_subject_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
