# Generated by Django 5.1.1 on 2025-03-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_alter_subject_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachersubject',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='teachersubject',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.DeleteModel(
            name='StudentSubject',
        ),
        migrations.DeleteModel(
            name='TeacherSubject',
        ),
    ]
