# Generated by Django 5.1.1 on 2025-02-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0006_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='50F3b0HHvjLWu1WhIW2HIR1mlBjAy9L5', editable=False, max_length=32, unique=True),
        ),
    ]
