# Generated by Django 5.1.1 on 2025-02-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0007_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='ND1nt0OoIbXbvTpwxgXUSjlcCEwYWn0g', editable=False, max_length=32, unique=True),
        ),
    ]
