# Generated by Django 5.1.1 on 2025-02-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0010_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='ILX0Ecu07LBXmSsSdKvjwVeu9NwNK01y', editable=False, max_length=32, unique=True),
        ),
    ]
