# Generated by Django 5.1.1 on 2025-02-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0011_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='ydoSIwnuKaI7qlqGdcoWKP2A855j4UzQ', editable=False, max_length=32, unique=True),
        ),
    ]
