# Generated by Django 5.1.1 on 2025-03-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0013_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='VF1JtpGN369x6lPCwWgmyImxPDL1EXUt', editable=False, max_length=32, unique=True),
        ),
    ]
