# Generated by Django 5.1.1 on 2025-03-24 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0018_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='vBVNk2OgumBvXHhZqiiu4S6R2oDt3uzn', editable=False, max_length=32, unique=True),
        ),
    ]
