# Generated by Django 5.1.1 on 2025-03-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0020_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='wuVTRsU4GVubrub6ws54yOVq6io0UWkV', editable=False, max_length=32, unique=True),
        ),
    ]
