# Generated by Django 5.1.1 on 2025-03-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0021_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='saMdm4BCjPqhvUHmVUVuDP49qXksNHdn', editable=False, max_length=32, unique=True),
        ),
    ]
